baseurl = "https://blog.ichi-h.com/"
languageCode = "ja"
Title = "blog.ichi-h.com"
theme = "hugo_theme_pickles"
copyright = "Copyright &copy; 2021 ichi"

HasCJKLanguage = true
summaryLength = 200

# Google Analytics API key.
# googleAnalytics = "Your Google Analytics tracking id"

[params]
  paginate = 10
  # Hide the date on posts
  # hideDate = true
  # Hide the word count on posts and in the posts list
  # hideWordCount = true
  # Hide the reading time on posts and in the posts list
  # hideReadingTime = true
  custom_css = ["/css/custom.css", "/css/link-card.css"]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "ichi_h3"
  # facebook = "Your Facebook username"
  # instagram = "Your Instagram username"
  github = "ichi-h"
  # gitlab = "Your GitLab username"
  # npm = "Your npm username"
  # codepen = "Your CodePen username"
  # dribbble = "Your Dribbble username"
  # fivehundredpx = "Your 500px username" # 500px
  # flickr = "Your Flickr username"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  # vimeo = "Your Vimeo username"
  # youtube = "Your YouTube username"
  # linkedin = "Your LinkedIn username"
  # medium = "Your Medium username"
  # strava = "Your Strava userid"
  # Disqus shortname
  # disqus = ""
  author = "ichi"
  authorwebsite = "ichi-h.com"
  avatar = "/images/ichi.jpg"
  # contact = "mailto:ichi.h3@gmail.com"
  bio = "創り続ける人生を選んだ人。音楽とプログラミングができる。この世にないものを創る。"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "創り続けること。"
  # Logo image. This is displayed ogp image.
  logo = "/images/ichi.jpg"
  favicon = "/images/favicon.ico"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Music"
    url = "/tags/music"
    weight = 3

[[menu.main]]
    name = "Development"
    url = "/tags/development"
    weight = 4

[[menu.main]]
    name = "Life"
    url = "/tags/life"
    weight = 5

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 6

[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 7

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
